### ISSUE TITLE
Using data in config of another task

### ISSUE THREAD

**Issue by gizburdt** [dylang/grunt-prompt#12]
Hi,

Love this grunt module :)
I would like to use this module in combination with grunt-contrib-copy. I would like to copy and rename a folder based on a input given in the prompt. Here is my Gruntfile.js: http://pastebin.com/CXSBae6h.

As you can see in the 'copy.theme' scope, I would like to copy wp-content/themes/scaffold-child/\* to wp-content/themes/' + grunt.config( 'conductor.project.name' ). When I run grunt, it creates a folder with name 'undefined'.

How can I use the prompt input within copy.theme? 

Thanks! :)

**Comment by aleross** [comment]
@dylang your second answer to this issue helped a lot. I was following the advice in the README in the "How can values be accessed from my own code?" section, where you recommend using `var validation = grunt.config('validation');` and kept getting `undefined`. I suspect many use-cases need to use the Grunt templating engine `<%= validation %>` instead because of the timing, and it might be worth adding a note about that.
